# Generated by Django 3.0.4 on 2020-05-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('ord', models.AutoField(db_column='ord', primary_key=True, serialize=False)),
                ('product_id', models.CharField(db_column='productID', max_length=10)),
                ('product_name', models.CharField(db_column='productName', max_length=25)),
                ('product_image', models.CharField(blank=True, db_column='productImage', max_length=100)),
                ('quantity', models.IntegerField(db_column='quantity')),
                ('price', models.IntegerField(db_column='sellPrice', default=0)),
                ('user', models.CharField(db_column='user', max_length=25)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(db_column='productID', max_length=10, primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_column='productName', max_length=25)),
                ('product_image', models.CharField(blank=True, db_column='productImage', max_length=100)),
                ('company', models.CharField(max_length=25)),
                ('product_description', models.TextField(db_column='productDescription')),
                ('quantity_in_stock', models.IntegerField(db_column='quantityInStock')),
                ('sell_price', models.IntegerField(db_column='sellPrice')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
