# Generated by Django 3.0.4 on 2020-04-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(db_column='productID', max_length=10, primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_column='productName', max_length=25)),
                ('product_image', models.CharField(blank=True, db_column='productImage', max_length=100)),
                ('company', models.CharField(max_length=25)),
                ('product_description', models.TextField(db_column='productDescription')),
                ('quantity_in_stock', models.IntegerField(db_column='quantityInStock')),
                ('sell_price', models.IntegerField(db_column='sellPrice')),
                ('buy_price', models.IntegerField(db_column='buyPrice')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
