# Generated by Django 3.0.4 on 2020-05-28 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(db_column='orderID', primary_key=True, serialize=False)),
                ('user', models.CharField(db_column='user', default='noname', max_length=25)),
                ('customer_name', models.CharField(db_column='customerName', default='noname', max_length=25)),
                ('address', models.CharField(db_column='address', default='nonexistent', max_length=100)),
                ('phone_number', models.CharField(db_column='phoneNumber', default='0000000000', max_length=15)),
                ('total_price', models.IntegerField(db_column='totalPrice', default=0)),
                ('shipped', models.BooleanField(db_column='shipped', default=False)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(db_column='productID', max_length=10)),
                ('user', models.CharField(db_column='user', max_length=25)),
                ('quantity', models.IntegerField(db_column='quantity')),
                ('order_id', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='products.Orders')),
                ('pd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'db_table': 'orderdetails',
                'unique_together': {('order_id', 'product_id')},
            },
        ),
    ]
