# Generated by Django 3.0.4 on 2020-04-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='ord',
            field=models.IntegerField(db_column='ord', primary_key=True, serialize=False),
        ),
    ]
