# Generated by Django 3.0.4 on 2020-04-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('ord', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('product_id', models.CharField(db_column='productID', max_length=10)),
                ('product_name', models.CharField(db_column='productName', max_length=25)),
                ('product_image', models.CharField(blank=True, db_column='productImage', max_length=100)),
                ('quantity', models.IntegerField(db_column='quantity')),
                ('price', models.IntegerField(db_column='sellPrice')),
                ('user', models.CharField(db_column='user', max_length=25)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
