# Generated by Django 3.0.4 on 2020-04-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='ord',
            field=models.AutoField(db_column='ord', primary_key=True, serialize=False),
        ),
    ]
