# Generated by Django 2.2.9 on 2020-04-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200420_0715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='buyprice',
            new_name='buy_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productdescription',
            new_name='product_description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productid',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productname',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantityinstock',
            new_name='quantity_in_stock',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sellprice',
            new_name='sell_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productimage',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.CharField(blank=True, db_column='productImage', max_length=100),
        ),
    ]
