# Generated by Django 3.0.4 on 2020-04-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200421_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.CharField(db_column='userID', default=0, max_length=25),
            preserve_default=False,
        ),
    ]
