# Generated by Django 2.2.9 on 2020-05-28 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200528_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='pd',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='pd',
        ),
        migrations.AlterField(
            model_name='cart',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
