# Generated by Django 3.0.4 on 2020-04-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200421_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.CharField(db_column='user', max_length=25),
        ),
    ]
