# Generated by Django 2.2.9 on 2020-05-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200528_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='shipped',
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(db_column='status', default='Pending', max_length=10),
        ),
    ]
