# Generated by Django 2.2.9 on 2020-04-26 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_orderdj'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDJ',
        ),
    ]
