# Generated by Django 2.2.9 on 2020-04-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_orderdj'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(db_column='orderID', max_length=10)),
                ('product_id', models.CharField(db_column='productID', max_length=10)),
                ('user', models.CharField(db_column='user', max_length=25)),
                ('product_name', models.CharField(db_column='productName', max_length=25)),
                ('quantity', models.IntegerField(db_column='quantity')),
                ('price', models.IntegerField(db_column='sellPrice')),
            ],
            options={
                'db_table': 'orderDJ',
                'unique_together': {('order_id', 'product_id')},
            },
        ),
    ]
