# Generated by Django 2.2.9 on 2020-05-29 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200528_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='customer_name',
            field=models.CharField(db_column='customer_name', default='noname', max_length=25),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.AutoField(db_column='order_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone_number',
            field=models.CharField(db_column='phone_number', default='0000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_price',
            field=models.IntegerField(db_column='total_price', default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(db_column='product_description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(db_column='product_id', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.CharField(blank=True, db_column='product_image', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(db_column='product_name', max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_in_stock',
            field=models.IntegerField(db_column='quantity_in_stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_price',
            field=models.IntegerField(db_column='sell_price'),
        ),
    ]
