# Generated by Django 2.2.9 on 2020-04-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_orderdj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdj',
            name='order_id',
            field=models.IntegerField(db_column='orderID'),
        ),
    ]
