# Generated by Django 2.2.9 on 2020-04-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200426_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdj',
            name='address',
            field=models.CharField(db_column='address', default='nonexistent', max_length=100),
        ),
        migrations.AddField(
            model_name='orderdj',
            name='customer_name',
            field=models.CharField(db_column='customerName', default='noname', max_length=25),
        ),
    ]
