# Generated by Django 2.2.9 on 2020-04-26 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200426_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdj',
            name='shipped',
            field=models.BooleanField(db_column='shipped', default=False),
        ),
        migrations.AlterField(
            model_name='orderdj',
            name='order_id',
            field=models.AutoField(db_column='orderID', primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='orderdj',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='orderdj',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orderdj',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='orderdj',
            name='id',
        ),
        migrations.RemoveField(
            model_name='orderdj',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderdj',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='orderdj',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='orderdj',
            name='quantity',
        ),
        migrations.CreateModel(
            name='OrderDetailsDJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(db_column='productID', max_length=10)),
                ('user', models.CharField(db_column='user', max_length=25)),
                ('customer_name', models.CharField(db_column='customerName', default='noname', max_length=25)),
                ('address', models.CharField(db_column='address', default='nonexistent', max_length=100)),
                ('product_name', models.CharField(db_column='productName', max_length=25)),
                ('quantity', models.IntegerField(db_column='quantity')),
                ('price', models.IntegerField(db_column='sellPrice')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.OrderDJ')),
            ],
            options={
                'db_table': 'orderDetailsDJ',
                'unique_together': {('order_id', 'product_id')},
            },
        ),
    ]
