# Generated by Django 2.2.9 on 2020-04-26 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200426_1536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDetailsDJ',
        ),
        migrations.DeleteModel(
            name='OrderDJ',
        ),
    ]
