# Generated by Django 2.2.9 on 2020-04-26 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200426_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDJ',
            fields=[
                ('order_id', models.AutoField(db_column='orderID', primary_key=True, serialize=False)),
                ('user', models.CharField(db_column='user', max_length=25)),
                ('shipped', models.BooleanField(db_column='shipped', default=False)),
            ],
            options={
                'db_table': 'orderDJ',
            },
        ),
        migrations.CreateModel(
            name='OrderDetailsDJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(db_column='productID', max_length=10)),
                ('user', models.CharField(db_column='user', max_length=25)),
                ('customer_name', models.CharField(db_column='customerName', default='noname', max_length=25)),
                ('address', models.CharField(db_column='address', default='nonexistent', max_length=100)),
                ('product_name', models.CharField(db_column='productName', max_length=25)),
                ('quantity', models.IntegerField(db_column='quantity')),
                ('price', models.IntegerField(db_column='sellPrice')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.OrderDJ')),
            ],
            options={
                'db_table': 'orderDetailsDJ',
                'unique_together': {('order_id', 'product_id')},
            },
        ),
    ]
