# Generated by Django 2.2.9 on 2020-04-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_orderdetailsdj_orderdj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetailsdj',
            name='order_id',
            field=models.IntegerField(db_column='orderID'),
        ),
    ]
