# Generated by Django 2.2.9 on 2020-04-27 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200426_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetailsdj',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.OrderDJ'),
        ),
    ]
