# Generated by Django 2.2.9 on 2020-04-27 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200427_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetailsdj',
            name='order_id',
            field=models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='products.OrderDJ'),
        ),
    ]
