# Generated by Django 2.2.9 on 2020-04-27 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_orderdj_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetailsdj',
            name='address',
        ),
    ]
