# Generated by Django 2.2.9 on 2020-04-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_orderdetailsdj_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetailsdj',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='orderdetailsdj',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='orderdj',
            name='user',
        ),
        migrations.AddField(
            model_name='orderdj',
            name='customer_name',
            field=models.CharField(db_column='customerName', default='noname', max_length=25),
        ),
    ]
