# Generated by Django 2.2.9 on 2020-04-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20200427_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.IntegerField(db_column='sellPrice', default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_id',
            field=models.CharField(db_column='productID', default='0000', max_length=10),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_image',
            field=models.CharField(blank=True, db_column='productImage', max_length=100),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_name',
            field=models.CharField(db_column='productName', default='noname', max_length=25),
        ),
    ]
