# Generated by Django 2.2.9 on 2020-04-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20200427_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_id',
            field=models.CharField(db_column='productID', max_length=10),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product_name',
            field=models.CharField(db_column='productName', max_length=25),
        ),
    ]
