# Generated by Django 3.0.4 on 2020-05-28 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20200429_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetailsdj',
            name='pd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
